[package]
name = "rehan"
version = "0.1.0"
edition = "2021"
default-run = "rehan"

[dependencies]
regex = "1.11.1"
strfmt = "0.2.4"
thiserror = "2.0.6"

[[bin]]
name = "rehan"
path = "src/main.rs"

[[bin]]
name = "rehan-prepare"
path = "src/rehan-prepare.rs"
